name: Blacklist Email
description: Report an email to be added to the blacklist
title: "[Report]: [EMAIL]"
labels: ["blacklist"]
assignees:
  - sefinek

body:
  - type: input
    id: email
    attributes:
      label: Email
      placeholder: "test@example.com"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      placeholder: "15.09.2024"
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content
      render: text
    validations:
      required: true
