name: Report Email Address
title: Report Email Address
description: ""
labels:
  - report
assignees: sefinek
body:
  - type: input
    id: input-0
    attributes:
      label: Reported Email Address
      description: Enter the email address you want to report.
  - type: input
    id: input-1
    attributes:
      label: Email Subject
      description: Provide the subject line of the email.
  - type: input
    id: input-2
    attributes:
      label: Date and Time Received
      description: Use format DD-MM-YYYY, HH:MM (e.g. 04.09.2024, 01:31).
  - type: textarea
    id: textarea-1
    attributes:
      label: Email Content
      description: Paste the full content of the email you are reporting.
  - type: textarea
    id: textarea-2
    attributes:
      label: Additional Information (optional)
      description: Add any extra details, such as how you received the email or relevant headers.
